version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:8080/api
      - VITE_PUBLIC_API_URL=http://localhost:8080/api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/AI_Study_DB
      - CORS_ALLOWED_ORIGINS=http://frontend:5173,http://localhost:5173
    depends_on:
      - mongodb
      - python-server   
    restart: unless-stopped

  python-server:
    container_name: aistudydocker-python-server   
    build: ./python-server
    ports:
      - "5000:5000"
    environment:
      - CHROMA_SERVER_HOST=chromadb   
    depends_on:
      - chromadb
    restart: unless-stopped

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma_data
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=AI_Study_DB
    restart: unless-stopped

volumes:
  chroma_data:
  mongo_data:

networks:
  default:
    name: aistudy-network
    driver: bridge